Matrix Operation-R


In [1]:
x <- matrix(
    nrow=4,
    ncol=2,
    data=c(1,2,3,4,5,6,7,8)
)
print(x)

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


In [2]:
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = c(1,2,3,4,5,6,7,8),
  byrow = FALSE
)

print(x)

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


In [3]:
y <- matrix(
  nrow = 4,
  ncol = 2,
  data = c(1,2,3,4,5,6,7,8),
  byrow = TRUE
)

print(y)


     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8


In [4]:
print(x[3,2])

[1] 7


In [5]:
print(x[1,1])
print(x[2,1])
print(x[4,2])


[1] 1
[1] 2
[1] 8


In [6]:
print(dim(x))

[1] 4 2


Number of rows

In [7]:
print(nrow(x))

[1] 4


Number of columns

In [9]:
print(ncol(x))

[1] 2


 Find mode/type

In [10]:
print(mode(x))

[1] "numeric"


Display attributes

In [11]:
print(attributes(x))

$dim
[1] 4 2



Check whether x is a matrix

In [12]:
print(is.matrix(x))


[1] TRUE


Convert vector to matrix

In [15]:
v <- c(1,2,3,4)
v_matrix <- as.matrix(v)
print(v_matrix)

     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4


Help/documentation for matrix

In [16]:
help("matrix")