# NPTEL R Programming – Week 7
## Complete Python / Google Colab Implementation

This notebook translates the Week 7 **Foundations of R Software** notes into Python.

### Lectures covered
- Lecture 26: More Sequences and Other Operations
- Lecture 27: Sequences of Dates and Alphabets
- Lecture 28: Repeats
- Lecture 29: Sorting, Ordering and Mode
- Lecture 30: Lists

The examples follow the terminology and examples in the uploaded NPTEL notes.


In [1]:
import numpy as np
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
import string
from collections import Counter

print("Week 7 Python notebook is ready!")


Week 7 Python notebook is ready!


# Lecture 26 – More Sequences and Other Operations

R's `seq()` generates regular sequences. The notes also demonstrate the `:` operator for unit-increment and unit-decrement sequences. fileciteturn3file0L11-L19


In [2]:
# R: 1:10, 10:1, 5:15, 15:5
print("1:10  ->", list(range(1, 11)))
print("10:1  ->", list(range(10, 0, -1)))
print("5:15  ->", list(range(5, 16)))
print("15:5  ->", list(range(15, 4, -1)))

print("-1:-10 ->", list(range(-1, -11, -1)))
print("-10:-1 ->", list(range(-10, 0)))
print("-5:-15 ->", list(range(-5, -16, -1)))
print("-15:-5 ->", list(range(-15, -4)))


1:10  -> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
10:1  -> [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
5:15  -> [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
15:5  -> [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5]
-1:-10 -> [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10]
-10:-1 -> [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1]
-5:-15 -> [-5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15]
-15:-5 -> [-15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5]


## Decimal sequences

The R `:` operator can also create sequences with a unit increment/decrement when the endpoints are numeric. fileciteturn3file0L54-L62


In [3]:
def r_colon_decimal(start, end, step=1.0):
    values = []
    x = float(start)
    if step > 0:
        while x <= end + 1e-12:
            values.append(round(x, 10))
            x += step
    else:
        while x >= end - 1e-12:
            values.append(round(x, 10))
            x += step
    return values

print(r_colon_decimal(1.23, 10))
print(r_colon_decimal(1.23, 10.54))
print(r_colon_decimal(10.54, 2.23, -1))
print(r_colon_decimal(-1.23, -10, -1))
print(r_colon_decimal(-5.23, 6, 1))


[1.23, 2.23, 3.23, 4.23, 5.23, 6.23, 7.23, 8.23, 9.23]
[1.23, 2.23, 3.23, 4.23, 5.23, 6.23, 7.23, 8.23, 9.23, 10.23]
[10.54, 9.54, 8.54, 7.54, 6.54, 5.54, 4.54, 3.54, 2.54]
[-1.23, -2.23, -3.23, -4.23, -5.23, -6.23, -7.23, -8.23, -9.23]
[-5.23, -4.23, -3.23, -2.23, -1.23, -0.23, 0.77, 1.77, 2.77, 3.77, 4.77, 5.77]


## `seq()` equivalents

The notes show `seq(10)` producing 1 through 10 and examples where `from`, `to`, and `by` are specified. fileciteturn3file0L82-L98


In [4]:
def seq_r(from_value=1, to_value=1, by=None, length_out=None):
    if length_out is not None:
        if length_out == 1:
            return [from_value]
        return np.linspace(from_value, to_value, length_out).tolist()
    if by is None:
        by = 1 if to_value >= from_value else -1
    values = []
    x = from_value
    if by > 0:
        while x <= to_value + 1e-12:
            values.append(x)
            x += by
    else:
        while x >= to_value - 1e-12:
            values.append(x)
            x += by
    return values

print("seq(10):", seq_r(1, 10))
print("seq(1, x, x/10), x=2:", seq_r(1, 2, 0.2))
print("seq(0, x, x/10), x=50:", seq_r(0, 50, 5))


seq(10): [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
seq(1, x, x/10), x=2: [1, 1.2, 1.4, 1.5999999999999999, 1.7999999999999998, 1.9999999999999998]
seq(0, x, x/10), x=50: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


## Store and operate on a sequence

The notes store `seq(1, 50, 1/2)` in `x`, then calculate `y = 2*x`. fileciteturn3file0L101-L118


In [5]:
x = np.arange(1, 50.5, 0.5)
y = 2 * x

print("First 20 values of x:", x[:20])
print("Last 10 values of x:", x[-10:])
print("First 20 values of y:", y[:20])


First 20 values of x: [ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]
Last 10 values of x: [45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5 50. ]
First 20 values of y: [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.
 20. 21.]


## Index vectors

R's `seq(along=x)` creates an index sequence corresponding to the positions of `x`. fileciteturn3file0L127-L135

Python uses **0-based indexing**, so the equivalent position values are `range(len(x))`.


In [6]:
x = [9, 8, 7, 6]
ind_r_style = [1, 2, 3, 4]

print("x:", x)
print("R-style index vector:", ind_r_style)
print("Second element of x:", x[1])  # R x[ind[2]]


x: [9, 8, 7, 6]
R-style index vector: [1, 2, 3, 4]
Second element of x: 8


# Lecture 27 – Sequences of Dates and Alphabets

The notes use `Sys.time()` for the current time/date and `Sys.Date()` for the current date. fileciteturn3file0L141-L150


In [7]:
now = datetime.now()
today = date.today()

print("Current date and time:", now)
print("Current date:", today)


Current date and time: 2026-10-01 09:01:15.029181
Current date: 2026-10-01


## Date sequences by year

R's date `seq()` supports increments such as `"day"`, `"week"`, `"month"`, `"quarter"` and `"year"`. fileciteturn3file0L173-L184


In [8]:
def date_sequence(start, count, unit):
    start = datetime.strptime(start, "%Y-%m-%d").date()
    result = []
    current = start

    for _ in range(count):
        result.append(current)
        if unit == "day":
            current += timedelta(days=1)
        elif unit == "week":
            current += timedelta(weeks=1)
        elif unit == "month":
            current += relativedelta(months=1)
        elif unit == "year":
            current += relativedelta(years=1)
        else:
            raise ValueError("Use day, week, month, or year")
    return result

print("Year sequence:")
print(date_sequence("2010-01-01", 8, "year"))

print("\nDay sequence:")
print(date_sequence("2017-01-01", 6, "day"))

print("\nMonth sequence:")
print(date_sequence("2017-01-01", 6, "month"))

print("\nYear sequence:")
print(date_sequence("2017-01-01", 6, "year"))


Year sequence:
[datetime.date(2010, 1, 1), datetime.date(2011, 1, 1), datetime.date(2012, 1, 1), datetime.date(2013, 1, 1), datetime.date(2014, 1, 1), datetime.date(2015, 1, 1), datetime.date(2016, 1, 1), datetime.date(2017, 1, 1)]

Day sequence:
[datetime.date(2017, 1, 1), datetime.date(2017, 1, 2), datetime.date(2017, 1, 3), datetime.date(2017, 1, 4), datetime.date(2017, 1, 5), datetime.date(2017, 1, 6)]

Month sequence:
[datetime.date(2017, 1, 1), datetime.date(2017, 2, 1), datetime.date(2017, 3, 1), datetime.date(2017, 4, 1), datetime.date(2017, 5, 1), datetime.date(2017, 6, 1)]

Year sequence:
[datetime.date(2017, 1, 1), datetime.date(2018, 1, 1), datetime.date(2019, 1, 1), datetime.date(2020, 1, 1), datetime.date(2021, 1, 1), datetime.date(2022, 1, 1)]


## Reverse monthly sequence

The notes generate a monthly sequence from `2017-01-01` backward to `2016-01-01`. fileciteturn3file0L227-L236


In [9]:
start = date(2017, 1, 1)
end = date(2016, 1, 1)

dates_backward = []
current = start

while current >= end:
    dates_backward.append(current)
    current -= relativedelta(months=1)

print(dates_backward)


[datetime.date(2017, 1, 1), datetime.date(2016, 12, 1), datetime.date(2016, 11, 1), datetime.date(2016, 10, 1), datetime.date(2016, 9, 1), datetime.date(2016, 8, 1), datetime.date(2016, 7, 1), datetime.date(2016, 6, 1), datetime.date(2016, 5, 1), datetime.date(2016, 4, 1), datetime.date(2016, 3, 1), datetime.date(2016, 2, 1), datetime.date(2016, 1, 1)]


## Alphabet sequences

R provides `letters` for lowercase alphabets and `LETTERS` for uppercase alphabets. fileciteturn3file0L245-L272


In [10]:

letters = list(string.ascii_lowercase)
LETTERS = list(string.ascii_uppercase)

print("Lowercase:", letters)
print("Uppercase:", LETTERS)

# R letters[1:3] -> Python letters[0:3]
print("letters[1:3] in R:", letters[0:3])
print("Reverse range c:b:a example:", letters[2::-1])
print("letters[21:23] in R:", letters[20:23])
print("letters[2] in R:", letters[1])

print("LETTERS[1:3] in R:", LETTERS[0:3])
print("LETTERS[3:1] in R:", LETTERS[2::-1])
print("LETTERS[21:23] in R:", LETTERS[20:23])
print("LETTERS[2] in R:", LETTERS[1])


Lowercase: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
Uppercase: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
letters[1:3] in R: ['a', 'b', 'c']
Reverse range c:b:a example: ['c', 'b', 'a']
letters[21:23] in R: ['u', 'v', 'w']
letters[2] in R: b
LETTERS[1:3] in R: ['A', 'B', 'C']
LETTERS[3:1] in R: ['C', 'B', 'A']
LETTERS[21:23] in R: ['U', 'V', 'W']
LETTERS[2] in R: B


# Lecture 28 – Repeats

R's `rep()` replicates numeric values, text, or vector values. Important forms include:
- `rep(x, times=n)` – repeat the whole vector
- `rep(x, each=n)` – repeat each element
- `rep(x, length.out=n)` – generate exactly the requested output length. fileciteturn3file0L300-L316


In [11]:
x = [1, 2, 3, 4]

print("rep(3.5, times=10):", [3.5] * 10)
print("rep(1:4, 2):", x * 2)

print("rep(x, times=3):", x * 3)
print("rep(x, each=3):", [value for value in x for _ in range(3)])


rep(3.5, times=10): [3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5]
rep(1:4, 2): [1, 2, 3, 4, 1, 2, 3, 4]
rep(x, times=3): [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
rep(x, each=3): [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]


## `each` and `times` together

The notes demonstrate `rep(1:4, each=2, times=3)` and show the effect of repeating each element before repeating the whole pattern. fileciteturn3file0L351-L360


In [12]:
pattern = [value for value in range(1, 5) for _ in range(2)]
result = pattern * 3

print("Pattern:", pattern)
print("Repeated 3 times:", result)


Pattern: [1, 1, 2, 2, 3, 3, 4, 4]
Repeated 3 times: [1, 1, 2, 2, 3, 3, 4, 4, 1, 1, 2, 2, 3, 3, 4, 4, 1, 1, 2, 2, 3, 3, 4, 4]


## Different repetition count for each element

The notes show `rep(1:4, 2:5)`, where the first element is repeated 2 times, the second 3 times, etc. fileciteturn3file0L368-L373


In [13]:
values = [1, 2, 3, 4]
counts = [2, 3, 4, 5]

result = []
for value, count in zip(values, counts):
    result.extend([value] * count)

print(result)


[1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4]


## Repetition counts generated by a sequence

The notes use `ans = seq(from=2, to=8, by=2)` and then `rep(1:4, ans)`. fileciteturn3file0L375-L382


In [14]:
ans = list(range(2, 9, 2))
values = [1, 2, 3, 4]

result = []
for value, count in zip(values, ans):
    result.extend([value] * count)

print("ans:", ans)
print("result:", result)


ans: [2, 4, 6, 8]
result: [1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4]


## Repeating a matrix

The notes demonstrate `rep()` on a 2×2 matrix. fileciteturn3file0L385-L393


In [15]:
x_matrix = np.array([[1, 2], [3, 4]])

# R rep(x, 3) follows R's column-major vectorization.
r_vector = x_matrix.flatten(order="F")
result = np.tile(r_vector, 3)

print("Matrix:")
print(x_matrix)
print("R-style repeated vector:", result)


Matrix:
[[1 2]
 [3 4]]
R-style repeated vector: [1 3 2 4 1 3 2 4 1 3 2 4]


## Repeating character vectors

In [16]:
print(["a", "b", "c"] * 2)
print(["apple", "banana", "cake"] * 2)

print([2] * 5)
print(([2, 3] * 3)[:5])
print(([2, 3, 4] * 2)[:5])

print(["apple"] * 5)
print((["a", "b", "c"] * 2)[:5])


['a', 'b', 'c', 'a', 'b', 'c']
['apple', 'banana', 'cake', 'apple', 'banana', 'cake']
[2, 2, 2, 2, 2]
[2, 3, 2, 3, 2]
[2, 3, 4, 2, 3]
['apple', 'apple', 'apple', 'apple', 'apple']
['a', 'b', 'c', 'a', 'b']


# Lecture 29 – Sorting, Ordering and Mode

R `sort()` sorts a vector in ascending order by default, with `decreasing=TRUE` for descending order. fileciteturn3file0L442-L453


In [17]:
y = [8, 5, 7, 6]

print("Original:", y)
print("Ascending:", sorted(y))
print("Descending:", sorted(y, reverse=True))


Original: [8, 5, 7, 6]
Ascending: [5, 6, 7, 8]
Descending: [8, 7, 6, 5]


## `order()` equivalent

R's `order()` returns the positions/indices that would sort a vector. For `y = c(9,8,5,7,6)`, the notes show `order(y) = 3,5,4,2,1`. fileciteturn3file0L482-L506


In [18]:
y = [9, 8, 5, 7, 6]

order_zero_based = sorted(range(len(y)), key=lambda i: y[i])
order_r_style = [i + 1 for i in order_zero_based]

print("y:", y)
print("Python zero-based order:", order_zero_based)
print("R-style 1-based order:", order_r_style)

order_desc = sorted(range(len(y)), key=lambda i: y[i], reverse=True)
order_desc_r_style = [i + 1 for i in order_desc]

print("R-style decreasing order:", order_desc_r_style)
print("Values in sorted order:", [y[i] for i in order_zero_based])


y: [9, 8, 5, 7, 6]
Python zero-based order: [2, 4, 3, 1, 0]
R-style 1-based order: [3, 5, 4, 2, 1]
R-style decreasing order: [1, 2, 4, 5, 3]
Values in sorted order: [5, 6, 7, 8, 9]


## R `mode()` versus statistical mode

In R, `mode()` describes how an object is stored in memory (for example numeric, character, list, function), rather than calculating the most frequent value. The notes give examples for numbers, character strings, factors, lists, data frames and functions. fileciteturn3file0L514-L540

Python does not have an exact `mode()` equivalent with the same R meaning. `type()` is the closest general inspection tool.


In [19]:
objects = {
    "number": 2.432,
    "numeric_vector": [3, 4, 5, 6, 7, 8],
    "character": "India",
    "character_vector": ["India", "CANADA"],
    "list": ["India", "USA"],
    "function": print
}

for name, obj in objects.items():
    print(f"{name:18} -> {type(obj)}")


number             -> <class 'float'>
numeric_vector     -> <class 'list'>
character          -> <class 'str'>
character_vector   -> <class 'list'>
list               -> <class 'list'>
function           -> <class 'builtin_function_or_method'>


### Python statistical mode (different concept)

If you want the **most frequent value** of a dataset, Python's `Counter` can be used. This is a statistical mode, not R's `mode()` storage-class concept.


In [20]:
data = [1, 2, 2, 3, 2, 4, 3, 2]
frequency = Counter(data)

print("Frequencies:", frequency)
print("Statistical mode:", frequency.most_common(1)[0][0])


Frequencies: Counter({2: 4, 3: 2, 1: 1, 4: 1})
Statistical mode: 2


# Lecture 30 – Lists

The notes distinguish lists from vectors, matrices and arrays:
- vectors generally contain one data type;
- lists can contain elements of different types;
- lists can contain structured objects such as matrices, data frames and other lists;
- list elements can be indexed by position and can have names. fileciteturn3file0L580-L610

Python's built-in `list` is a natural equivalent because it can contain objects of different types.


In [21]:
# A heterogeneous Python list
z = [
    "India",
    25,
    3.14,
    [1, 2, 3],
    np.array([[1, 2], [3, 4]])
]

for i, item in enumerate(z, start=1):
    print(f"Element {i}: type={type(item).__name__}, value={item}")


Element 1: type=str, value=India
Element 2: type=int, value=25
Element 3: type=float, value=3.14
Element 4: type=list, value=[1, 2, 3]
Element 5: type=ndarray, value=[[1 2]
 [3 4]]


## Matrix examples

The notes first create two 2×2 matrices and add them. fileciteturn3file0L617-L631


In [22]:
x1 = np.array([[1, 2], [3, 4]])
x2 = np.array([[5, 6], [7, 8]])

print("x1:")
print(x1)

print("\nx2:")
print(x2)

print("\nx1 + x2:")
print(x1 + x2)


x1:
[[1 2]
 [3 4]]

x2:
[[5 6]
 [7 8]]

x1 + x2:
[[ 6  8]
 [10 12]]


## Why mixing text into a numeric matrix changes the data

The notes show assigning `"hello"` to one matrix element, after which the matrix becomes character data and numeric addition is no longer valid. fileciteturn3file0L635-L643

Python/NumPy illustrates the same idea through an array with a common string dtype.


In [23]:
x1_mixed = np.array([[1, 2], [3, 4]], dtype=object)
x1_mixed[1, 0] = "hello"

print(x1_mixed)

try:
    print(x1_mixed + x2)
except Exception as e:
    print("Addition error:", e)


[[1 2]
 ['hello' 4]]
Addition error: can only concatenate str (not "int") to str


## List containing matrices

The notes create `matlist = list(x1, x2)`, producing a list whose elements are matrices. fileciteturn3file0L647-L675


In [24]:
matlist = [x1, x2]

print("matlist[0]:")
print(matlist[0])

print("\nmatlist[1]:")
print(matlist[1])


matlist[0]:
[[1 2]
 [3 4]]

matlist[1]:
[[5 6]
 [7 8]]


## List containing different object types

The notes create a list containing:
1. a character vector,
2. a repeated numeric vector,
3. a matrix. fileciteturn3file0L694-L706


In [25]:
z1 = [
    ["water", "juice", "lemonade"],
    [value for value in range(1, 5) for _ in range(2)],
    np.array([[5, 6], [7, 8]])
]

for i, item in enumerate(z1, start=1):
    print(f"Element {i}:")
    print(item)
    print()


Element 1:
['water', 'juice', 'lemonade']

Element 2:
[1, 1, 2, 2, 3, 3, 4, 4]

Element 3:
[[5 6]
 [7 8]]



## Accessing list elements

R uses `[[ ]]` to extract an element from a list. The notes specifically show `z1[[1]]` and then extracting `"juice"` from that element. fileciteturn3file0L714-L723

Python uses ordinary list indexing with square brackets and **0-based** positions.


In [26]:
print("First element:", z1[0])
print("Second item of first element:", z1[0][1])

# R z1[[1]][2] -> Python z1[0][1]


First element: ['water', 'juice', 'lemonade']
Second item of first element: juice


# Week 7 Practice Exercises

In [27]:
# 1. Generate a sequence from 10 to 100 by 10
sequence = list(range(10, 101, 10))
print(sequence)

# 2. Generate lowercase letters from f to m
print(letters[5:13])

# 3. Repeat [1,2,3] three times
print([1, 2, 3] * 3)

# 4. Repeat each element three times
print([v for v in [1, 2, 3] for _ in range(3)])

# 5. Sort a list
values = [15, 3, 10, 7, 2]
print(sorted(values))

# 6. Get ordering indices
order = sorted(range(len(values)), key=lambda i: values[i])
print([i + 1 for i in order])

# 7. Build a heterogeneous list
practice_list = [100, "Python", 3.14, [1, 2], np.array([[1, 2], [3, 4]])]
print(practice_list)


[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
['f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 1, 1, 2, 2, 2, 3, 3, 3]
[2, 3, 7, 10, 15]
[5, 2, 4, 3, 1]
[100, 'Python', 3.14, [1, 2], array([[1, 2],
       [3, 4]])]


# R → Python Quick Reference

| R concept/function | Python equivalent |
|---|---|
| `1:10` | `range(1, 11)` |
| `seq()` | `range()`, `numpy.arange()`, `numpy.linspace()` |
| `Sys.time()` | `datetime.now()` |
| `Sys.Date()` | `date.today()` |
| Date `seq(..., by="days")` | `timedelta` loop |
| Date `seq(..., by="months")` | `relativedelta(months=1)` |
| `letters` | `string.ascii_lowercase` |
| `LETTERS` | `string.ascii_uppercase` |
| `rep(x, times=n)` | `x * n` |
| `rep(x, each=n)` | list comprehension |
| `rep(..., length.out=n)` | repeat then slice / `itertools.cycle` |
| `sort(x)` | `sorted(x)` |
| `sort(x, decreasing=TRUE)` | `sorted(x, reverse=True)` |
| `order(x)` | sorted index positions |
| R `mode()` | `type()` for storage/type inspection |
| R statistical mode | `Counter(...).most_common()` |
| `list()` | Python `list` |
| `x[[i]]` | `x[i-1]` conceptually, with Python's 0-based indexing |


# End of Week 7

Use **Runtime → Run all** in Google Colab to execute the complete notebook.

**Note:** Python indexing starts at 0, while the R examples in the notes use 1-based indexing. The notebook explicitly shows R-style positions where needed.
